export const REGISTER_SUCCESS = 'REGISTER_SUCCES';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const APPLY_SELLER = 'APPLY_SELLER';
export const VERIFY_EMAIL = 'VERIFY_EMAIL';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';

export const FETCH_SERVICEBYCATEGORY = 'FETCH_SERVICEBYCATEGORY';
export const FETCH_SERVICE = 'FETCH_SERVICE';
export const FETCH_DETAILSERVICE = 'FETCH_DETAILSERVICE';
export const FETCH_TOPSERVICE = 'FETCH_TOPSERVICE';
export const FETCH_SERVICE_BYSLUG = 'FETCH_SERVICE_BYSLUG';
export const CREATE_SERVICE = 'CREATE_SERVICE';
export const FETCH_MY_SERVICE = 'FETCH_MY_SERVICE';
export const DELETE_SERVICE = 'DELETE_SERVICE';

export const FETCH_PACKAGES = 'FETCH_PACKAGES';
export const FETCH_PACKAGES_BYSLUG = 'FETCH_PACKAGES_BYSLUG';
export const CREATE_PACKAGES = 'CREATE_PACKAGES';
export const DELETE_PACKAGES = 'DELETE_PACKAGES';
export const EDIT_PACKAGES = 'EDIT_PACKAGES';

export const FETCH_REVIEW = 'FETCH_REVIEW';
export const FETCH_REVIEW_BYSLUG = 'FETCH_REVIEW_BYSLUG';
export const CREATE_REVIEW = 'CREATE_REVIEW';

export const FETCH_ORDER_USER = 'FETCH_ORDER_USER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const FETCH_SELLER_ORDER_NEW = 'FETCH_SELLER_ORDER_NEW';
export const PATCH_SELLER_ORDER_NEW = 'PATCH_SELLER_ORDER_NEW';
export const FETCH_ORDER_PROGRESS = 'FETCH_ORDER_PROGRESS';
export const FETCH_ORDER_APPROVE = 'FETCH_ORDER_APPROVE';
export const ORDER_FILE_UPLOAD = 'ORDER_FILE_UPLOAD';
export const SET_DETAIL_ORDER = 'SET_DETAIL_ORDER';
export const DELETE_DETAIL_ORDER = 'DELETE_DETAIL_ORDER';
export const PATCH_ORDER_DONE = 'PATCH_ORDER_DONE';
export const REVISING_ORDER = 'REVISING_ORDER';
export const APPROVE_ORDER = 'APPROVE_ORDER';

export const FETCH_NOTIF = 'FETCH_NOTIF';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_SELLER = 'FETCH_SELLER';
export const APPROVE_SELLER = 'APPROVE_SELLER';
export const REJECT_SELLER = 'REJECT_SELLER';

export const GET_NEW_ORDER_DETAIL_SELLER = 'GET_NEW_ORDER_DETAIL_SELLER';
export const HIDE_NEW_ORDER_DETAIL_SELLER = 'HIDE_NEW_ORDER_DETAIL_SELLER';
export const GET_ONPROGRESS_ORDER_DETAIL_SELLER = 'GET_ONPROGRESS_ORDER_DETAIL_SELLER';
export const HIDE_ONPROGRESS_ORDER_DETAIL_SELLER = 'HIDE_ONPROGRESS_ORDER_DETAIL_SELLER';

export const FETCH_MY_SELLER = 'FETCH_MY_SELLER';

export const GET_NEW_SELLER_DETAIL = 'GET_NEW_SELLER_DETAIL';
export const HIDE_NEW_SELLER_DETAIL = 'HIDE_NEW_SELLER_DETAIL';

export const SEND_PAYMENT = 'SEND_PAYMENT';

export const SWITCH_TO_SELLER = 'SWITCH_TO_SELLER';
export const SWITCH_TO_BUYER = 'SWITCH_TO_BUYER';