export const REGISTER_SUCCESS = 'REGISTER_SUCCES';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const APPLY_SELLER = 'APPLY_SELLER';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const FETCH_CATEGORY = 'FETCH_CATEGORY';

export const FETCH_SERVICEBYCATEGORY = 'FETCH_SERVICEBYCATEGORY';
export const FETCH_SERVICE = 'FETCH_SERVICE';
export const FETCH_DETAILSERVICE = 'FETCH_DETAILSERVICE';
export const FETCH_TOPSERVICE = 'FETCH_TOPSERVICE';
export const FETCH_SERVICE_BYSLUG = 'FETCH_SERVICE_BYSLUG';

export const FETCH_PACKAGES = 'FETCH_PACKAGES';
export const FETCH_PACKAGES_BYSLUG = 'FETCH_PACKAGES_BYSLUG';
export const CREATE_PACKAGES = 'CREATE_PACKAGES';
export const DELETE_PACKAGES = 'DELETE_PACKAGES';
export const EDIT_PACKAGES = 'EDIT_PACKAGES';

export const FETCH_REVIEW = 'FETCH_REVIEW';
export const FETCH_REVIEW_BYSLUG = 'FETCH_REVIEW_BYSLUG';

export const FETCH_ORDER_USER = 'FETCH_ORDER_USER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const FETCH_SELLER_ORDER_NEW = 'FETCH_SELLER_ORDER_NEW';
export const PATCH_SELLER_ORDER_NEW = 'PATCH_SELLER_ORDER_NEW';
export const FETCH_ORDER_PROGRESS = 'FETCH_ORDER_PROGRESS';
export const ORDER_FILE_UPLOAD = 'ORDER_FILE_UPLOAD';

export const FETCH_NOTIF = 'FETCH_NOTIF';

export const FETCH_USER = 'FETCH_USER';

export const GET_NEW_ORDER_DETAIL_SELLER = 'GET_NEW_ORDER_DETAIL_SELLER';
export const HIDE_NEW_ORDER_DETAIL_SELLER = 'HIDE_NEW_ORDER_DETAIL_SELLER';
export const GET_ONPROGRESS_ORDER_DETAIL_SELLER = 'GET_ONPROGRESS_ORDER_DETAIL_SELLER';
export const HIDE_ONPROGRESS_ORDER_DETAIL_SELLER = 'HIDE_ONPROGRESS_ORDER_DETAIL_SELLER';

export const FETCH_MY_SELLER = 'FETCH_MY_SELLER';

export const SEND_PAYMENT = 'SEND_PAYMENT';